In [1]:
import pandas as pd
import numpy as np
import numpy as numpy
import sys
import os
import scipy.stats as stats
from statistics import mean
from enum import Enum
import sys
print(sys.version)
import math

from scipy.spatial.distance import euclidean
from fastdtw import fastdtw
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
print("TensorFlow version:", tf.__version__)

class DB(Enum):
    Mcyt=0
    eBioSignDS1=1
    eBioSignDS2=3
    BiosecurID=4
    BiosecureDS2=5
    EvalDB=6

class Signature:
    def __init__(self, data, filePath):
        self.data = data
        self.filePath = filePath
        pathParts= filePath.split('/')
        self.fileName=pathParts[4]
        self.inputDevice=pathParts[2]
        if "signature" in filePath:
            self.db='EvalDb'
            self.inputDevice='Unknown'
            return
        
        parts=pathParts[4].split('_')
        signerId=parts[0][1:]
        self.db=self.getDatabase(pathParts[2],pathParts[3],int(signerId))
        #print(self.db)
        pressureColumn=self.getPressureColumn()
        
        self.x=data[:, 0].tolist()
        self.y=data[:, 1].tolist()
        self.t=data[:, 2].tolist()
        self.pressure=data[:, pressureColumn]
        
        if (self.inputDevice == "Unkown"):
            self.inputDevice=getInputDeviceForEvalDb()
        
        self.correctZeroTime()
        self.correctSameTimestamps()
    
        if self.inputDevice == 'stylus':
            i=0
            while len(self.pressure) > 0 and self.pressure[0] == 0:
                self.x.pop(0)
                self.y.pop(0)
                self.t.pop(0)
                self.pressure.pop(0)

            while (len(self.pressure) > 0 and self.pressure[len(self.pressure)-1] == 0):
                self.x.pop(len(self.pressure)-1)
                self.y.pop(len(self.pressure)-1)
                self.t.pop(len(self.pressure)-1)
                self.pressure.pop(len(self.pressure)-1)
        
        self.dx=difference(self.x)
        self.dy=difference(self.y)
        
        self.calculatePathTangentAngle()
        self.calculatePVM()
        self.dpvm=difference(self.pvm)
        self.dpta=difference(self.pta)
        self.lcr=self.calculateLCR()
        self.dlcr=difference(self.lcr)
        
        self.calculateTotalAccelerationMagnitude()
        self.dtam=difference(self.tam)
        #self.pta=math.atan(self.dy/self.dx)
        #self.pvm=math.sqrt(self.dx**2+self.dy*2)
        #self.dx=self.x.diff()
        #self.lcr=math.log(self.pvm/self.pta,10)

        self.x=normalize(self.x)
        self.y=normalize(self.y)
    
        if self.inputDevice != "finger":
            self.dpressure=difference(self.pressure)
            self.dpressure=normalize(self.dpressure)    
            self.pressure=normalize(self.pressure)
        
        self.pvm=normalize(self.pvm)
        self.pta=normalize(self.pta)
        self.tam=normalize(self.tam)
        self.dpvm=normalize(self.dpvm)
        self.dpta=normalize(self.dpta)
        self.dlcr=normalize(self.dlcr)
        
        self.ddx=difference(self.dx)
        self.ddy=difference(self.dy)
        
        self.ndarrayx=np.ndarray(shape=1)
        
        '''
        print('self.x') 
        print(self.x) 
        print(self.filePath) 
        print(self.dx)  
        print(self.dy)
        print(self.dpressure)
        print(self.pta)
        print(self.pvm)
        #print(self.lcr)
        print(self.tam)
        '''
    
    def calculatePathTangentAngle(self):
        self.pta=[]
        for i in range(0,len(self.dx)):
            if(self.dx[i]==0):
                self.pta.append(math.atan(self.dy[i]/(self.dx[i] + 0.0000000000000001)))
            else:
                self.pta.append(math.atan(self.dy[i]/self.dx[i]))
        
    def calculatePVM(self):
        self.pvm=[]
        for i in range(0,len(self.dx)):
            self.pvm.append(math.sqrt(self.dx[i]**2+self.dy[i]**2))
            
    def calculateLCR(self):
        lcr=[]
        for i in range(0,len(self.dpta)):
            value=0
            if(self.dpta[i]==0):
                value=self.pvm[i]/(self.dpta[i]+0.0000000000000001)
            else:
                value=self.pvm[i]/self.dpta[i]
            value=abs(value)
            if(value<=0):
                '''
                print("value<=0 at index:")
                print(i)
                print('value:')
                print(value)
                print('self.dx')
                print(self.dx)
                print('self.dy') 
                print(self.dy)
                print('self.pta') 
                print(self.pta)
                print('self.dpta') 
                print(self.dpta)
                print('self.pvm')
                print(self.pvm)
                '''
                lcr.append(math.log(value+0.0000000000000001,10))
            else:
                lcr.append(math.log(value,10))
                
        return lcr
    
    def calculateTotalAccelerationMagnitude(self):
        self.tam=[]
        for i in range(0,len(self.dpvm)):
            self.pta.append(math.sqrt(self.dpvm[i]**2+(self.pvm[i]**2)*(self.pta[i]**2)))
            
    def getPressureColumn(self):
        if self.db==DB.Mcyt:
            return 5
        elif self.db==DB.BiosecurID:
            return 6
        elif self.db==DB.BiosecureDS2:
            return 6
        elif self.db==DB.eBioSignDS1:
            return 3
        elif self.db==DB.eBioSignDS2:
            return 3
        elif self.db==DB.EvalDB:
            return 3
        
    def getDatabase(self, split, inputDevice, signerId):
        '''
        print(split)
        print(inputDevice)
        print(signerId)
        '''
        if split=='Development':
            if inputDevice=='finger':
                if 1009<=signerId<=1038:
                    return DB.eBioSignDS1
                elif 1039<=signerId<=1084:
                    return DB.eBioSignDS2
                else:
                    print("Undefined DB for file: {file}")
            elif inputDevice=="stylus":
                if 1<=signerId<=230: 
                    return DB.Mcyt
                elif 231<=signerId<=498:
                    return DB.BiosecurID
                elif 1009<=signerId<=1038:
                    return DB.eBioSignDS1
                elif 1039<=signerId<=1084:
                    return DB.eBioSignDS2
                else:
                    print("Undefined DB for file: {file}")
            else:
                print("Undefined InputDevice for file: {file}")
        elif split=='Evaluation':
            if inputDevice=='finger':
                if 373<=signerId<=407:
                    return DB.eBioSignDS1
                elif 408<=signerId<=442:
                    return DB.eBioSignDS2
                else:
                    print("Undefined DB for file: {file}")
            elif inputDevice=="stylus":
                if 1<=signerId<=100:
                    return DB.Mcyt
                elif 101<=signerId<=232:
                    return DB.BiosecurID
                elif 233<=signerId<=372:
                    return DB.BiosecureDS2
                elif 373<=signerId<=407:
                    return DB.eBioSignDS1
                elif 408<=signerId<=442:
                    return DB.eBioSignDS2
                else:
                    print("Undefined DB for file: {file}")
            else:
                print("Undefined InputDevice for file: {file}")
        else:
            print("Undefined InputDevice for file: {file}")
            
    def getInputDeviceForEvalDb(self):
        for i in range(0, len(self.pressure), 1):
            if self.pressure[i]!=0:
                return False

        return True
    
    def isAllZero(self):
        for i in range(0, self.data.shape[0], 1):
            if self.data[i,0]!=0:
                return False

        return True
    
    def correctZeroTime(self):
        if self.isAllZero():
            for i in range(0, self.data.shape[0], 1):
                self.data[i,0]=i*10
                
    def correctSameTimestamps(self):
        i=0
        while i < self.data.shape[0]-1:
            if self.data[i,0]==self.data[i+1,0]:
                self.data=np.delete(self.data, i, 0)
            else:
                i += 1

def readFilesInDir(dirPath, allFiles):
    print('asdasd')
    signatureFiles = os.listdir(dirPath)
    i=0
    for file in signatureFiles:
        print(i)
        dataframe=pd.read_csv(dirPath + '/' + file,sep=' ',skiprows=[0],header=None)
        array=np.array(dataframe)
        signature=Signature(array,dirPath + '/' + file)
        allFiles.append(signature)
        if i%100==0:
            print(i)
        i+=1
        
def readSignaturesInComparison(comparison, allFiles):
        dataframe=pd.read_csv(dirPath + '/' + comparison.file1,sep=' ',skiprows=[0],header=None)
        array=np.array(dataframe)
        signature=Signature(array,dirPath + '/' + comparison.file1)
        allFiles.append(signature)
        comparison.signature1=signature
        
        dataframe=pd.read_csv(dirPath + '/' + comparison.file2,sep=' ',skiprows=[0],header=None)
        array=np.array(dataframe)
        signature=Signature(array,dirPath + '/' + comparison.file2)
        allFiles.append(signature)
        comparison.signatur2=signature

3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)]
TensorFlow version: 2.8.0


In [2]:
class Comparison:
    def __init__(self, file1, file2, label, filePath):
        self.file1=file1
        self.file2=file2
        self.label=label
        self.filePath=filePath
        
def readComparisonFile(filePath, comparisons):
    dataframe=pd.read_csv(filePath,sep=' ',header=None)
    array=dataframe.to_numpy()
    #print(array)
    #print(len(array[:, 0]))
    for i in range(0,len(array[:, 0])-1):
        comparison=Comparison(array[i,0],array[i,1],array[i,2],filePath)
        comparisons.append(comparison)

In [3]:
def difference(dataset, interval=1):
    diff = []
    for i in range(interval, len(dataset)):
        value = dataset[i] - dataset[i - interval]
        diff.append(value)
        
    return diff

def Average(lst):
    return sum(lst) / len(lst)

def normalizeX(allFiles):
    all=[]
    for item in allFiles:
        all=all+item.x
    
    #print('xAll')
    #print(xAll)
    #average=mean(xAll)
    z = stats.zscore(all)
    #print(average)
    print(z)
    allIndex=0
    
    for item in allFiles:
        for i in range(0,len(item.x),1):
            item.x[i]=z[allIndex]
            allIndex+=1
            
    print('Normalized x:')
    for item in allFiles:
        print(item.x)
    '''
    for item in allFiles:
        for i in range(0,len(item.x),1):
            item.x[i]=(item.x[i]-average)/z
    '''
def normalizeY(allFiles):
    all=[]
    for item in allFiles:
        all=all+item.y
    z = stats.zscore(all)
    print(z)
    
    allIndex=0
    for item in allFiles:
        for i in range(0,len(item.y),1):
            item.y[i]=z[allIndex]
            allIndex+=1
            
    print('Normalized y:')
    for item in allFiles:
        print(item.y)
            
def normalizePressure(allFiles):
    all=[]
    for item in allFiles:
        all=all+item.pressure
    z = stats.zscore(all)
    print(z)
    
    allIndex=0
    for item in allFiles:
        for i in range(0,len(item.pressure),1):
            item.pressure[i]=z[allIndex]
            allIndex+=1
            
    print('Normalized pressure:')
    for item in allFiles:
        print(item.filePath)
        print(item.pressure)

def normalize(data):
    normalized=[]
    z = stats.zscore(data)
    #print(z)

    for i in range(0,len(data),1):
        normalized.append(z[i])
            
    return normalized
'''
for item in normalized:
        print(item)
        
    return normalized
'''
    
        
def normalizeY2(allFiles):
    for item in allFiles:
        z = stats.zscore(item.y)
        print(z)

        for i in range(0,len(item.y),1):
            item.y[i]=z[i]

    print('Normalized y:')
    for item in allFiles:
        print(item.y)
        
def normalizePressure2(allFiles):
    for item in allFiles:
        z = stats.zscore(item.pressure)
        print('item.pressure:')
        print(item.pressure)
        print('z:')
        print(z)

        for i in range(0,len(item.pressure),1):
            item.pressure[i]=z[i]

    print('Normalized pressure:')
    for item in allFiles:
        print("item.filePath")
        print(item.pressure)


In [4]:
def dtw(s, t):
    n, m = len(s), len(t)
    dtw_matrix = np.zeros((n+1, m+1))
    for i in range(n+1):
        for j in range(m+1):
            dtw_matrix[i, j] = np.inf
    dtw_matrix[0, 0] = 0

    for i in range(1, n+1):
        for j in range(1, m+1):
            cost = abs(s[i-1] - t[j-1])
            # take last min from a square box
            last_min = np.min([dtw_matrix[i-1, j], dtw_matrix[i, j-1], dtw_matrix[i-1, j-1]])
            dtw_matrix[i, j] = cost + last_min
    return dtw_matrix

def getAlignment(tf1,tf2):
    distance, path=fastdtw(tf1, tf2, dist=euclidean)
    alignedX=[]
    alignedY=[]
    for tuple in path:
        alignedX.append(tf1[tuple[0]])
        alignedY.append(tf2[tuple[1]])
    alignedX=np.array(alignedX)
    alignedY=np.array(alignedY)
    return (alignedX,alignedY)

def alignTimeFunctions(signature1,signature2):
    alignedFunctions=getAlignment(signature1.x,signature2.x)
    signature1.dtwx=alignedFunctions[0]
    signature2.dtwx=alignedFunctions[1]
    
    alignedFunctions=getAlignment(signature1.y,signature2.y)
    signature1.dtwy=alignedFunctions[0]
    signature2.dtwy=alignedFunctions[1]
    
def alignAllComparisons(comparisons,allFiles):
    for i in range(0,len(comparisons)):
        print('findok')
        comparisons[i].signature1=findByPath(allFiles,comparisons[i].file1)
        comparisons[i].signature2=findByPath(allFiles,comparisons[i].file2)
        print('findok')
        #signature1=next((x for x in allFiles if x.fileName == comparisons[i].file1), None)
        #signature2=next((x for x in allFiles if x.fileName == comparisons[i].file2), None)
        if comparisons[i].signature1 is None or comparisons[i].signature2 is None:
            print('valamelyik signature nem található')
            print('i:')
            print(comparisons[i].file1)
            print(comparisons[i].file2)
            for file in allFiles:
                print(file.fileName)
        print('dtw')
        alignTimeFunctions(comparisons[i].signature1,comparisons[i].signature2)
        print('dtw')
        #comparisons[i].signature1.dtwx=comparisons[i].signature1.dtwx.astype("float32")
    
def dtwAllX(comparisons,allFiles):
    comparisonCount=len(comparisons)
    for i in range(0,comparisonCount):
        print('findok')
        signature1=findByPath(allFiles,comparisons[i].file1)
        signature2=findByPath(allFiles,comparisons[i].file2)
        print('findok')
        #signature1=next((x for x in allFiles if x.fileName == comparisons[i].file1), None)
        #signature2=next((x for x in allFiles if x.fileName == comparisons[i].file2), None)
        if signature1 is None or signature2 is None:
            print('valamelyik signature nem található')
            print('i:')
            print(comparisons[i].file1)
            print(comparisons[i].file2)
            for file in allFiles:
                print(file.fileName)
        print('dtw')
        #dtwOutputs.append(fastdtw(signature1.x, signature2.x, dist=euclidean))
        distance, path=fastdtw(signature1.x, signature2.x, dist=euclidean)
        distance, comparisons[i].dtwy=fastdtw(signature1.y, signature2.y, dist=euclidean)
        if(signature1.inputDevice=='stylus'):
            distance, comparisons[i].dtwpressure=fastdtw(signature1.pressure, signature2.pressure, dist=euclidean)
            distance, comparisons[i].dtwdpressure=fastdtw(signature1.dpressure, signature2.dpressure, dist=euclidean)
        distance, comparisons[i].dtwdx=fastdtw(signature1.dx, signature2.dx, dist=euclidean)
        distance, comparisons[i].dtwdy=fastdtw(signature1.dy, signature2.dy, dist=euclidean)
        distance, comparisons[i].dtwpta=fastdtw(signature1.pta, signature2.pta, dist=euclidean)
        distance, comparisons[i].dtwpvm=fastdtw(signature1.pvm, signature2.pvm, dist=euclidean)
        
        distance, comparisons[i].dtwdpvm=fastdtw(signature1.dpvm, signature2.dpvm, dist=euclidean)
        distance, comparisons[i].dtwdpta=fastdtw(signature1.dpta, signature2.dpta, dist=euclidean)
        distance, comparisons[i].dtwlcr=fastdtw(signature1.lcr, signature2.lcr, dist=euclidean)
        distance, comparisons[i].dtwdlcr=fastdtw(signature1.dlcr, signature2.dlcr, dist=euclidean)
        distance, comparisons[i].dtwtam=fastdtw(signature1.tam, signature2.tam, dist=euclidean)
        distance, comparisons[i].dtwdtam=fastdtw(signature1.dtam, signature2.dtam, dist=euclidean)
        
        distance, comparisons[i].dtwddx=fastdtw(signature1.ddx, signature2.ddx, dist=euclidean)
        distance, comparisons[i].dtwddy=fastdtw(signature1.ddy, signature2.ddy, dist=euclidean) 
        #comparisons[i].dtwx=np.array(comparisons[i].dtwx,np.dtype('int,int'))
        normalizer = tf.keras.layers.Normalization(axis=None)
        comparisons[i].dtwx=convertTuplesToMatrix(comparisons[i].dtwx)
        comparisons[i].dtwx=comparisons[i].dtwx.astype("float32")
        #comparisons[i].dtwx=normalizer.adapt(comparisons[i].dtwx)
        #comparisons[i].dtwx = stats.zscore(comparisons[i].dtwx)
        #print('dtw')
        #print(comparisons[i].dtwddx)
        print(str(i)+'/'+str(comparisonCount))
        if i==10:
            return

def findByPath(allFiles,filePath):
    for file in allFiles:
        if file.fileName==filePath:
            return file
        
def findByPath(allFiles,filePath):
    for file in allFiles:
        if file.fileName==filePath:
            return file
         
def convertTuplesToMatrix(tupleList):
    array=np.array(int)
    for t in tupleList:
        array=np.append(array, t[0])
        array=np.append(array, t[1])
    
    array=np.delete(array,0)
    max=np.amax(array)
    
    for i in range(array.size):
        array[i]=array[i]/max
        
    return array        

In [5]:

allFiles=[]
   
print('Reading signature files started')
#readFilesInDir('C:/DeepSignDB/Evaluation/stylus',allFiles)
readFilesInDir('D:/DeepSignSmallc/Evaluation/finger',allFiles)
#readFilesInDir('C:/DeepSignDB/Development/stylus',allFiles)
#readFilesInDir('C:/DeepSignDB/Development/finger',allFiles)
print('Reading signature files done')

comparisonFiles=[]
print('Reading comparison files started')
#readComparisonFile('C:/DeepSignDB/Comparison_Files/stylus/1vs1/random/Comp_DeepSignDB_random_stylus_1vs1.txt',comparisonFiles)
#readComparisonFile('C:/DeepSignDB/Comparison_Files/stylus/1vs1/skilled/Comp_DeepSignDB_skilled_stylus_1vs1.txt',comparisonFiles)
readComparisonFile('D:/DeepSignSmallc/Comparison_Files/finger/1vs1/random/Comp_DeepSignDB_random_finger_1vs1.txt',comparisonFiles)
#readComparisonFile('C:/DeepSignDB/Comparison_Files_small/finger/1vs1/skilled/Comp_DeepSignDB_skilled_finger_1vs1.txt',comparisonFiles)
print('Reading comparison files done')

'''
readFilesInDir('D:/DeepSignSmall/Evaluation/stylus',allFiles)
readFilesInDir('D:/DeepSignSmall/Evaluation/finger',allFiles)
readFilesInDir('D:/DeepSignSmall/Development/stylus',allFiles)
readFilesInDir('D:/DeepSignSmall/Development/finger',allFiles)

#readComparisonFile('D:/DeepSignSmall/Comparison_Files/stylus/1vs1/random/Comp_DeepSignDB_random_stylus_1vs1.txt',comparisonFiles)
#readComparisonFile('D:/DeepSignSmall/Comparison_Files/stylus/1vs1/skilled/Comp_DeepSignDB_skilled_stylus_1vs1.txt',comparisonFiles)
#readComparisonFile('D:/DeepSignSmall/Comparison_Files/finger/1vs1/random/Comp_DeepSignDB_random_finger_1vs1.txt',comparisonFiles)
readComparisonFile('D:/DeepSignSmall/Comparison_Files/finger/1vs1/skilled/Comp_DeepSignDB_skilled_finger_1vs1.txt',comparisonFiles)
'''
'''
print('Comparison files:')
for comparisonFile in comparisonFiles:
    print(comparisonFile.file1)
    print(comparisonFile.file2)
    print(comparisonFile.label)
    print(comparisonFile.filePath)
'''

'''
for file in allFiles:
    #print(file.data)
    #print(file.filePath)
    #print(file.db)
    #print(file.pressure)
'''

print('Allfiles:')
#print(allFiles)
print('Loading data finished')
alignAllComparisons(comparisonFiles,allFiles)

Reading signature files started
asdasd
0
0
1
2
3
4
Reading signature files done
Reading comparison files started
Reading comparison files done
Allfiles:
Loading data finished
findok
findok
dtw
dtw
findok
findok
dtw
dtw
findok
findok
dtw
dtw


In [6]:
def maxLengthArrayInList(list):
    print("Type list",type(list))
    print("Shape",list.shape)
    print("Value",list)
    for i in list:
        print("Type",type(i))
        print("Value",i)
    list_len = [len(i) for i in list]
    return list_len

def maxLengthArrayInComparisonFiles(comparisonFiles):
    maxvalue=0
    maxi=0
    for i in range(0,len(comparisonFiles)):
        if maxvalue < len(comparisonFiles[i].signature1.dtwx):
            maxvalue=len(comparisonFiles[i].signature1.dtwx)
        if maxvalue < len(comparisonFiles[i].signature2.dtwx):
            maxvalue=len(comparisonFiles[i].signature2.dtwx)
    
    return maxvalue

batch_size=len(comparisonFiles)
maxLength=maxLengthArrayInComparisonFiles(comparisonFiles)
featureCount=1

train_signatures1 = np.ndarray(shape=(batch_size,maxLength,featureCount),dtype=np.ndarray)
train_signatures2 = np.ndarray(shape=(batch_size,maxLength,featureCount),dtype=np.ndarray)
train_labels=np.empty(0)

for i in range(0,len(comparisonFiles)):
    for j in range(0,len(comparisonFiles[i].signature1.dtwx)):
        #print("i",i)
        #print("len(train_signatures1)",len(train_signatures1))
        #print("type(np.asarray(comparisonFiles[i].signature1.dtwx[j]))",type(np.asarray(comparisonFiles[i].signature1.dtwx[j])))
        #print("type(train_signatures1[i][j])",type(train_signatures1[i][j]))
        train_signatures1[i][j]=np.asarray(comparisonFiles[i].signature1.dtwx[j])
        
    for j in range(len(comparisonFiles[i].signature1.dtwx),maxLength):
        train_signatures1[i][j]=0
        
    for j in range(0,len(comparisonFiles[i].signature2.dtwx)):
        train_signatures2[i][j]=np.asarray(comparisonFiles[i].signature2.dtwx[j])
    
    for j in range(len(comparisonFiles[i].signature2.dtwx),maxLength):
        train_signatures2[i][j]=0
        
        
    train_labels=np.append(train_labels,comparisonFiles[i].label)
    print('train_labels')
    print(train_labels)

def maskZero(train_signatures1,train_signatures2): 
    for i in range(0,len(train_signatures1)):
        if len(train_signatures1[i])!=len(train_signatures2[i]):
            maxLength=max(len(train_signatures1[i]),len(train_signatures2[i]))
            if len(train_signatures1[i])>len(train_signatures2[i]):
                for j in range(len(train_signatures2[i]),maxLength):
                    train_signatures2[i]=np.append(train_signatures2[i],0)
            if len(train_signatures1[i])<len(train_signatures2[i]):
                for j in range(len(train_signatures1[i]),maxLength):
                    train_signatures1[i]=np.append(train_signatures1[i],0)
                    
def maskZero2(train_signatures1,train_signatures2,maxLength):
    allSignatures=np.append(train_signatures1,train_signatures2)
    
    for i in range(0,len(train_signatures1)):
        for j in range(0,maxLength-len(train_signatures1[i])):
            train_signatures1[i].append(np.float32(0),axis=0)
            
    for i in range(0,len(train_signatures2)):
        for j in range(0,maxLength-len(train_signatures2[i])):
            train_signatures2[i].append(np.float32(0),axis=0)
    


train_labels
[0.]
train_labels
[0. 0.]
train_labels
[0. 0. 1.]


In [7]:
train_labels=np.asarray(train_labels, dtype="uint8")
#train_labels=train_labels.reshape(1,-1) ha uncommentelelve van, akkor data cardinality is ambigous

print('train_signatures1')
print(train_signatures1.shape)
print(train_signatures1)
print('train_signatures2')
print(train_signatures2.shape)
print(train_signatures2)
print('train_labels')
print(train_labels.shape)
print(train_labels)

print('train_signatures1 shapes:')
print(train_signatures1.shape)
print(train_signatures1[0].shape)
print(train_signatures1[0][0].shape)

print('train_signatures1 types:')
print(type(train_signatures1))
print(type(train_signatures1[0]))
print(type(train_signatures1[0][0]))

input_signature1 = tf.keras.Input(
    shape=(maxLength,1), name="signature1"
)
input_signature2 = tf.keras.Input(
    shape=(maxLength,1), name="signature2"
)
bgru1=tf.keras.layers.Bidirectional(tf.keras.layers.GRU(2, return_sequences=True,name="gru1"),name="bidirectional1",input_shape=(batch_size,maxLength,1))(input_signature1)
bgru2=tf.keras.layers.Bidirectional(tf.keras.layers.GRU(2, return_sequences=True,name="gru2"),name="bidirectional2",input_shape=(batch_size,maxLength,1))(input_signature2)
concatenate = tf.keras.layers.concatenate([bgru1, bgru2])
bgru3=tf.keras.layers.Bidirectional(tf.keras.layers.GRU(1, return_sequences=True,name="gru3"))(concatenate)
flatten=tf.keras.layers.Flatten()(bgru3)
feed_forward=tf.keras.layers.Dense(1, activation='sigmoid', name="feed_forward")(flatten)
model = tf.keras.Model(
    inputs=[input_signature1, input_signature2],
    outputs=[feed_forward]
)

model.compile(loss='binary_crossentropy', optimizer='adam')

loss_fn = tf.keras.losses.BinaryCrossentropy(from_logits=False)

model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['binary_crossentropy'])

#maskZero2(train_signatures1,train_signatures2,maxLength)

train_signatures1=train_signatures1.astype(dtype=np.float32)
train_signatures2=train_signatures2.astype(dtype=np.float32)

#other conversion method:
#train_signatures1=train_signatures1.astype("float32")
#train_signatures2=train_signatures2.astype("float32")

print('train_signatures1')
print(train_signatures1.shape)
print(type(train_signatures1))
for i in train_signatures1:
    print(i)
#print(train_signatures1)
print('train_signatures2')
print(train_signatures2.shape)
print(type(train_signatures2))
#print(train_signatures2)
for i in train_signatures2:
    print(i)
print('train_labels')
print(train_labels.shape)
print(type(train_labels))
print(train_labels)

print('train_signatures1 shapes:')
print(train_signatures1.shape)
print(train_signatures1[0].shape)
print(train_signatures1[0][0].shape)

print('train_signatures1 types:')
print(type(train_signatures1))
print(type(train_signatures1[0]))
print(type(train_signatures1[0][0]))

model.summary()

model.fit(
    {"signature1": train_signatures1, "signature2": train_signatures2},
    {"feed_forward": train_labels},
    epochs=20,
    batch_size=32,
)

model.evaluate(
    {"signature1": train_signatures1, "signature2": train_signatures2},
    {"feed_forward": train_labels},
    verbose=2
)

probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

probability_model(train_signatures[:5])

train_signatures1
(3, 438, 1)
[[[-0.22956366221312535]
  [-0.22956366221312535]
  [-0.22956366221312535]
  ...
  [-0.6226803828707757]
  [-0.6226803828707757]
  [-0.6226803828707757]]

 [[-0.22956366221312535]
  [-0.22956366221312535]
  [-0.22956366221312535]
  ...
  [-0.6226803828707757]
  [-0.6226803828707757]
  [-0.6226803828707757]]

 [[-0.22956366221312535]
  [-0.22956366221312535]
  [-0.22956366221312535]
  ...
  [-0.6226803828707757]
  [-0.6226803828707757]
  [-0.6226803828707757]]]
train_signatures2
(3, 438, 1)
[[[-0.23289796107148744]
  [-0.23289796107148744]
  [-0.23289796107148744]
  ...
  [0]
  [0]
  [0]]

 [[0.0028009058062879455]
  [0.0028009058062879455]
  [0.0028009058062879455]
  ...
  [0]
  [0]
  [0]]

 [[-1.494738288327357]
  [-1.494738288327357]
  [-1.494738288327357]
  ...
  [1.5387359654327355]
  [1.5387359654327355]
  [1.5387359654327355]]]
train_labels
(3,)
[0 0 1]
train_signatures1 shapes:
(3, 438, 1)
(438, 1)
(1,)
train_signatures1 types:
<class 'numpy.ndarray

__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 signature1 (InputLayer)        [(None, 438, 1)]     0           []                               
                                                                                                  
 signature2 (InputLayer)        [(None, 438, 1)]     0           []                               
                                                                                                  
 bidirectional1 (Bidirectional)  (None, 438, 4)      60          ['signature1[0][0]']             
                                                                                                  
 bidirectional2 (Bidirectional)  (None, 438, 4)      60          ['signature2[0][0]']             
                                                                                                  
 concatena

AssertionError: Exception encountered when calling layer "model" (type Functional).

Could not compute output KerasTensor(type_spec=TensorSpec(shape=(None, 1), dtype=tf.float32, name=None), name='feed_forward/Sigmoid:0', description="created by layer 'feed_forward'")

Call arguments received:
  • inputs=tf.Tensor(shape=(None, 438, 1), dtype=float32)
  • training=None
  • mask=None